/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import BLL.Equipos;
/**
 *
 * @author CARR
 */
public class MantOrAskGUI extends javax.swing.JFrame {

    /**
     * Creates new form MantOrAskGUI
     */
    
     private final String nombre; 
     private final BLL.Usuarios user;
     private final javax.swing.JPanel jp;

    public MantOrAskGUI(String nombre, BLL.Usuarios user, javax.swing.JPanel jp) {
        this.nombre = nombre;
		this.user = user;
		this.jp = jp;
        initComponents();
    }
     
        
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        _tituloAccion = new javax.swing.JLabel();
        _equipo = new javax.swing.JLabel();
        equipoLbl = new javax.swing.JLabel();
        _usuario = new javax.swing.JLabel();
        usuarioLbl = new javax.swing.JLabel();
        pedirMantencionRB = new javax.swing.JRadioButton();
        reporteUltimaMantencionRB = new javax.swing.JRadioButton();
        reporteUltimaSolicitudRB = new javax.swing.JRadioButton();
        reporteEquipoFechaRB = new javax.swing.JRadioButton();
        comentarUltimaRB = new javax.swing.JRadioButton();
        _desde = new javax.swing.JLabel();
        desdeDC = new com.toedter.calendar.JDateChooser();
        _hasta = new javax.swing.JLabel();
        hastaDC = new com.toedter.calendar.JDateChooser();
        realizarUltimaMantencionRB = new javax.swing.JRadioButton();
        solicitarBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelNombreE = new javax.swing.JLabel();
        jLabelEquipo1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaInfo = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        _tituloAccion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        _tituloAccion.setForeground(new java.awt.Color(90, 105, 110));
        _tituloAccion.setText("Seleccionar Acción");
        _tituloAccion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        _equipo.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        _equipo.setText("Equipo:");

        equipoLbl.setText("----");

        _usuario.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        _usuario.setText("Usuario");

        usuarioLbl.setText("----");

        buttonGroup2.add(pedirMantencionRB);
        pedirMantencionRB.setText("Pedir Mantención");
        pedirMantencionRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedirMantencionRBActionPerformed(evt);
            }
        });

        buttonGroup2.add(reporteUltimaMantencionRB);
        reporteUltimaMantencionRB.setText("Reporte última Mantención del equipo");
        reporteUltimaMantencionRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteUltimaMantencionRBActionPerformed(evt);
            }
        });

        buttonGroup2.add(reporteUltimaSolicitudRB);
        reporteUltimaSolicitudRB.setText("Reporte última solicitud");
        reporteUltimaSolicitudRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteUltimaSolicitudRBActionPerformed(evt);
            }
        });

        buttonGroup2.add(reporteEquipoFechaRB);
        reporteEquipoFechaRB.setText("Reporte del equipo por fecha");
        reporteEquipoFechaRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteEquipoFechaRBActionPerformed(evt);
            }
        });

        buttonGroup2.add(comentarUltimaRB);
        comentarUltimaRB.setText("Comentar la última solicitud");

        _desde.setText("Desde");

        desdeDC.setEnabled(false);

        _hasta.setText("Hasta");

        hastaDC.setEnabled(false);

        buttonGroup2.add(realizarUltimaMantencionRB);
        realizarUltimaMantencionRB.setText("Realizar última mantención");
        realizarUltimaMantencionRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarUltimaMantencionRBActionPerformed(evt);
            }
        });

        solicitarBtn.setText("Solicitar");
        solicitarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(_hasta)
                            .addComponent(_desde))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(desdeDC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hastaDC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(_tituloAccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(solicitarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reporteEquipoFechaRB)
                            .addComponent(reporteUltimaSolicitudRB)
                            .addComponent(pedirMantencionRB)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(_equipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(equipoLbl)
                                .addGap(78, 78, 78)
                                .addComponent(_usuario)
                                .addGap(18, 18, 18)
                                .addComponent(usuarioLbl))
                            .addComponent(reporteUltimaMantencionRB)
                            .addComponent(realizarUltimaMantencionRB)
                            .addComponent(comentarUltimaRB))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_tituloAccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_equipo)
                    .addComponent(_usuario)
                    .addComponent(equipoLbl)
                    .addComponent(usuarioLbl))
                .addGap(29, 29, 29)
                .addComponent(pedirMantencionRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reporteUltimaMantencionRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reporteUltimaSolicitudRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reporteEquipoFechaRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comentarUltimaRB)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(desdeDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_desde))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hastaDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_hasta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(realizarUltimaMantencionRB)
                .addGap(39, 39, 39)
                .addComponent(solicitarBtn)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelNombreE.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabelNombreE.setText("Equipo: ");

        jLabelEquipo1.setText("----");

        jTextAreaInfo.setColumns(20);
        jTextAreaInfo.setLineWrap(true);
        jTextAreaInfo.setRows(5);
        jTextAreaInfo.setWrapStyleWord(true);
        jTextAreaInfo.setAutoscrolls(false);
        jScrollPane1.setViewportView(jTextAreaInfo);

        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelNombreE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelEquipo1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreE)
                    .addComponent(jLabelEquipo1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void solicitarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitarBtnActionPerformed
        // TODO add your handling code here:
        try{
        if (this.pedirMantencionRB.isSelected()) {
            new MantencionesGUI(this.nombre,this.user, this.jp).setVisible(true);
            dispose();
        }
        if (this.reporteUltimaMantencionRB.isSelected()) {
            new BLL.Reporte(this.nombre).ReporteU();
            dispose();
        }
        if(this.reporteUltimaSolicitudRB.isSelected()){
            new BLL.Reporte(this.nombre).Reporte();
        }
        if(this.reporteEquipoFechaRB.isSelected()){
            System.out.println(desdeDC.getDate());
            new BLL.Reporte(this.desdeDC.getDate(), 
                    this.hastaDC.getDate(), nombre);
            dispose();
        }
        if(this.realizarUltimaMantencionRB.isSelected()){
            new AccionesGUI(nombre, this.jp, this.user).setVisible(true);
            dispose();
        }
        if(this.comentarUltimaRB.isSelected()){
            new ModificarGUI(nombre, this.jp, this.user).setVisible(true);
            dispose();
        }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"no hay datos para mostrar");
            System.out.println(ex.getMessage());                   
        }
            
    }//GEN-LAST:event_solicitarBtnActionPerformed

    private void realizarUltimaMantencionRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarUltimaMantencionRBActionPerformed
        // TODO add your handling code here:
        this.desdeDC.setEnabled(false);
        this.hastaDC.setEnabled(false);
        
    }//GEN-LAST:event_realizarUltimaMantencionRBActionPerformed

    private void reporteUltimaMantencionRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteUltimaMantencionRBActionPerformed
        // TODO add your handling code here:
        this.desdeDC.setEnabled(false);
        this.hastaDC.setEnabled(false);
    }//GEN-LAST:event_reporteUltimaMantencionRBActionPerformed

    private void pedirMantencionRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedirMantencionRBActionPerformed
        // TODO add your handling code here:
        this.desdeDC.setEnabled(false);
        this.hastaDC.setEnabled(false);
    }//GEN-LAST:event_pedirMantencionRBActionPerformed

    private void reporteUltimaSolicitudRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteUltimaSolicitudRBActionPerformed
        // TODO add your handling code here:
        this.desdeDC.setEnabled(false);
        this.hastaDC.setEnabled(false);
    }//GEN-LAST:event_reporteUltimaSolicitudRBActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Equipos es = new Equipos(nombre);
        this.equipoLbl.setText(nombre);
        this.jLabelEquipo1.setText(nombre);
        this.jTextAreaInfo.setEditable(false);
        this.jTextAreaInfo.setText(es.readInfo().get("informacion"));
        String path = es.readInfo().get("imagen");
        URL url = this.getClass().getResource(path);
        ImageIcon icon = new ImageIcon(url);
        this.jLabel6.setIcon(icon);
        this.usuarioLbl.setText(this.user.getNombre());
        this.realizarUltimaMantencionRB.setVisible(user.isBkb());
    }//GEN-LAST:event_formWindowOpened

    private void reporteEquipoFechaRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteEquipoFechaRBActionPerformed
        // TODO add your handling code here:
        this.desdeDC.setEnabled(true);
        this.hastaDC.setEnabled(true);

    }//GEN-LAST:event_reporteEquipoFechaRBActionPerformed
      
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MantOrAskGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MantOrAskGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MantOrAskGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MantOrAskGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MantOrAskGUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _desde;
    private javax.swing.JLabel _equipo;
    private javax.swing.JLabel _hasta;
    private javax.swing.JLabel _tituloAccion;
    private javax.swing.JLabel _usuario;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton comentarUltimaRB;
    private com.toedter.calendar.JDateChooser desdeDC;
    private javax.swing.JLabel equipoLbl;
    private com.toedter.calendar.JDateChooser hastaDC;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelEquipo1;
    private javax.swing.JLabel jLabelNombreE;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaInfo;
    private javax.swing.JRadioButton pedirMantencionRB;
    private javax.swing.JRadioButton realizarUltimaMantencionRB;
    private javax.swing.JRadioButton reporteEquipoFechaRB;
    private javax.swing.JRadioButton reporteUltimaMantencionRB;
    private javax.swing.JRadioButton reporteUltimaSolicitudRB;
    private javax.swing.JButton solicitarBtn;
    private javax.swing.JLabel usuarioLbl;
    // End of variables declaration//GEN-END:variables
}
