/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.Manteciones;
import BLL.Usuarios;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JViewport;

/**
 *
 * @author CARR
 */
public class TrozadosIluminariasGui extends javax.swing.JPanel {

    /**
     * Creates new form TrozadoGUI
     */
    private BLL.Usuarios user;
    
    TrozadoIluminariasImagen t = new TrozadoIluminariasImagen(this.user, this);
    
    public TrozadosIluminariasGui(BLL.Usuarios user) {
        initComponents();
        this.user = user;
        this.colores();        
        //t.setBounds(0,0,200,200);
        this.jScrollPane2.setViewportView(t);
//        JViewport vw = this.jScrollPane1.getViewport();
//        vw.add(t);
//        vw.setPreferredSize(new Dimension(400,400));
//        //this.jScrollPane1.getViewport().setView(vw);
        //this.jScrollPane2.setPreferredSize(new Dimension(400,400));
        //        this.jScrollPane1.revalidate();
        
        //repaint();
//        this.jPanel1.add(new Imagener("/GUI/Alumbrado Division Insdustrial "
//                + "Sopraval Rev. 2 - 2015 "
//                + "(cambio entretecho)-Presentación1.png", jp.getSize()));
      
    }

  
    
    
    public void colores(){
//        this.jButton1.setBackground(this.colorear(jButton1.getText()));
//        this.jButton2.setBackground(this.colorear(jButton2.getText()));
//        this.jButton3.setBackground(this.colorear(jButton3.getText()));
//        this.jButton4.setBackground(this.colorear(jButton4.getText()));
//        this.jButton5.setBackground(this.colorear(jButton5.getText()));
//        this.jButton6.setBackground(this.colorear(jButton6.getText()));
        }
    public Color colorear(String equipo){
        return new Manteciones(equipo).colorear();
    }
    
     
   
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jButtonReporteArea = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setAutoscrolls(true);
        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(400, 400));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TROZADO");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel1, java.awt.BorderLayout.NORTH);

        jScrollPane2.setMaximumSize(new java.awt.Dimension(600, 600));
        add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jButtonReporteArea.setText("Reporte Area");
        jButtonReporteArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReporteAreaActionPerformed(evt);
            }
        });
        add(jButtonReporteArea, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReporteAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReporteAreaActionPerformed
        //        // TODO add your handling code here:
                new ReportesPorArea(1,1).setVisible(true);
    }//GEN-LAST:event_jButtonReporteAreaActionPerformed
//    private void nuevaVentana(String nombre){
//        new MantOrAskGUI(nombre, this.user, this).setVisible(true);
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReporteArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
