/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.Manteciones;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author CARR
 */
public class TrozadosIluminariasGui11 extends javax.swing.JPanel {

    /**
     * Creates new form TrozadoGUI
     */
    private BLL.Usuarios user;
    private Image image;
    public TrozadosIluminariasGui11(BLL.Usuarios user) {
        initComponents();
        this.user = user;
        this.image = new ImageIcon(getClass().getResource("/GUI/Alumbrado "
                + "Division Insdustrial Sopraval Rev. 2 - 2015 "
                + "(cambio entretecho)-Presentación1.png")).getImage();
                
        this.colores();
        this.jPanel1.repaint();
    }
    
    public void colores(){
//        this.jButton1.setBackground(this.colorear(jButton1.getText()));
//        this.jButton2.setBackground(this.colorear(jButton2.getText()));
//        this.jButton3.setBackground(this.colorear(jButton3.getText()));
//        this.jButton4.setBackground(this.colorear(jButton4.getText()));
//        this.jButton5.setBackground(this.colorear(jButton5.getText()));
//        this.jButton6.setBackground(this.colorear(jButton6.getText()));
        }
    private Color colorear(String equipo){
        return new Manteciones(equipo).colorear();
    }
    
     @Override
        public void paint(Graphics g) {
        g.drawImage(image, 0, 0, getWidth(), getHeight(),
                        this);
 
        setOpaque(false);
        super.paint(g);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonReporteArea = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setToolTipText("");
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1739, Short.MAX_VALUE)
        );

        jButtonReporteArea.setText("Reporte Area");
        jButtonReporteArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReporteAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 599, Short.MAX_VALUE)
                        .addComponent(jButtonReporteArea)
                        .addGap(0, 599, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonReporteArea))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReporteAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReporteAreaActionPerformed
        // TODO add your handling code here:
        new ReportesPorArea(1,1).setVisible(true);
    }//GEN-LAST:event_jButtonReporteAreaActionPerformed
    private void nuevaVentana(String nombre){
        new MantOrAskGUI(nombre, this.user, this).setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReporteArea;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
