/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.Manteciones;
import BLL.Usuarios;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JViewport;

/**
 *
 * @author CARR
 */
public class TrozadosIluminariasGui extends javax.swing.JPanel {

	/**
	 * Creates new form TrozadoGUI
	 */
	private BLL.Usuarios user;

	TrozadoIluminariasImagen t = new TrozadoIluminariasImagen(this);

	public TrozadosIluminariasGui() {
		initComponents();
		this.user = Main.Main.user;
		//this.colores();        
		this.planoScrollPane.setViewportView(t);
	}

	public void colores() {
//        this.jButton1.setBackground(this.colorear(jButton1.getText()));
//        this.jButton2.setBackground(this.colorear(jButton2.getText()));
//        this.jButton3.setBackground(this.colorear(jButton3.getText()));
//        this.jButton4.setBackground(this.colorear(jButton4.getText()));
//        this.jButton5.setBackground(this.colorear(jButton5.getText()));
//        this.jButton6.setBackground(this.colorear(jButton6.getText()));
	}

	public Color colorear(String equipo) {
		return new Manteciones(equipo).colorear();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloLbl = new javax.swing.JLabel();
        planoScrollPane = new javax.swing.JScrollPane();
        reporteAreaBtn = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setAutoscrolls(true);
        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(400, 400));
        setLayout(new java.awt.BorderLayout());

        tituloLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tituloLbl.setForeground(new java.awt.Color(102, 102, 102));
        tituloLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLbl.setText("TROZADO");
        tituloLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tituloLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(tituloLbl, java.awt.BorderLayout.NORTH);

        planoScrollPane.setMaximumSize(new java.awt.Dimension(600, 600));
        add(planoScrollPane, java.awt.BorderLayout.CENTER);

        reporteAreaBtn.setText("Reporte Area");
        reporteAreaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteAreaBtnActionPerformed(evt);
            }
        });
        add(reporteAreaBtn, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void reporteAreaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteAreaBtnActionPerformed
		//        // TODO add your handling code here:
		new ReportesPorArea(1, 1).setVisible(true);
    }//GEN-LAST:event_reporteAreaBtnActionPerformed
//    private void nuevaVentana(String nombre){
//        new MantOrAskGUI(nombre, this.user, this).setVisible(true);
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane planoScrollPane;
    private javax.swing.JButton reporteAreaBtn;
    private javax.swing.JLabel tituloLbl;
    // End of variables declaration//GEN-END:variables
}
