package Main;

import GUI.EmpaqueEvaporadoresGui;
import GUI.EmpaqueIluminariasGui;
import GUI.MenuGui;
import GUI.ProcesosPosterioresIluminariasGui;
import GUI.TrozadoEvaporadoresGui;
import GUI.TrozadosIluminariasGui;
import javax.swing.JOptionPane;

/**
 *
 * @author CARR
 */
public class Main extends javax.swing.JFrame {

	private BLL.Usuarios user;
        public static Main instancia;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        user = new BLL.Usuarios();
        instancia = this;
    }
	
    public void cambioVentana(javax.swing.JPanel jp){
        jp.setPreferredSize(contenedorPanel.getSize());
        this.contenedorPanel.removeAll();
        this.contenedorPanel.add(jp);
        this.contenedorPanel.updateUI();
        this.contenedorPanel.repaint();
        repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        contenedorPanel = new javax.swing.JPanel();
        ingresoPanel = new javax.swing.JPanel();
        tituloPanel = new javax.swing.JPanel();
        tituloLbl = new javax.swing.JLabel();
        logoBtn = new javax.swing.JButton();
        formularioPanel = new javax.swing.JPanel();
        nombreLbl = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        contrasenaLbl = new javax.swing.JLabel();
        contrasenaTxt = new javax.swing.JPasswordField();
        entrarBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        areaMenu = new javax.swing.JMenu();
        menuGeneralItem = new javax.swing.JMenuItem();
        trozadoItem = new javax.swing.JMenu();
        trozado_iluminariasItem = new javax.swing.JMenuItem();
        trozado_evaporadoresItem = new javax.swing.JMenuItem();
        empaqueItem = new javax.swing.JMenu();
        empaque_iluminariasItem = new javax.swing.JMenuItem();
        empaque_evaporadoresItem = new javax.swing.JMenuItem();
        procesosPosterioresItem = new javax.swing.JMenu();
        procesosPosteriores_iluminariasItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        contenedorPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        contenedorPanel.setLayout(new javax.swing.BoxLayout(contenedorPanel, javax.swing.BoxLayout.LINE_AXIS));

        ingresoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ingresoPanel.setLayout(new java.awt.GridBagLayout());

        tituloPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        tituloPanel.setPreferredSize(new java.awt.Dimension(411, 50));

        tituloLbl.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        tituloLbl.setForeground(new java.awt.Color(75, 113, 125));
        tituloLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLbl.setText("DEMO");
        tituloLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tituloPanel.add(tituloLbl);

        logoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sopraval.png"))); // NOI18N
        logoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoBtnActionPerformed(evt);
            }
        });
        tituloPanel.add(logoBtn);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.ipady = 72;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        ingresoPanel.add(tituloPanel, gridBagConstraints);

        formularioPanel.setLayout(new java.awt.GridBagLayout());

        nombreLbl.setText("Nombre: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 11, 0);
        formularioPanel.add(nombreLbl, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 11, 0);
        formularioPanel.add(nombreTxt, gridBagConstraints);

        contrasenaLbl.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        formularioPanel.add(contrasenaLbl, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        formularioPanel.add(contrasenaTxt, gridBagConstraints);

        entrarBtn.setForeground(new java.awt.Color(65, 95, 105));
        entrarBtn.setText("Entrar");
        entrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 180;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        formularioPanel.add(entrarBtn, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        ingresoPanel.add(formularioPanel, gridBagConstraints);

        contenedorPanel.add(ingresoPanel);

        getContentPane().add(contenedorPanel);

        areaMenu.setText("AREA");
        areaMenu.setEnabled(false);

        menuGeneralItem.setText("Menu General");
        menuGeneralItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGeneralItemActionPerformed(evt);
            }
        });
        areaMenu.add(menuGeneralItem);

        trozadoItem.setText("Trozado");

        trozado_iluminariasItem.setText("Iluminarias");
        trozado_iluminariasItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trozado_iluminariasItemActionPerformed(evt);
            }
        });
        trozadoItem.add(trozado_iluminariasItem);

        trozado_evaporadoresItem.setText("Evaporadores");
        trozado_evaporadoresItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trozado_evaporadoresItemActionPerformed(evt);
            }
        });
        trozadoItem.add(trozado_evaporadoresItem);

        areaMenu.add(trozadoItem);

        empaqueItem.setText("Empaque");

        empaque_iluminariasItem.setText("Iluminarias");
        empaque_iluminariasItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empaque_iluminariasItemActionPerformed(evt);
            }
        });
        empaqueItem.add(empaque_iluminariasItem);

        empaque_evaporadoresItem.setText("Evaporadores");
        empaque_evaporadoresItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empaque_evaporadoresItemActionPerformed(evt);
            }
        });
        empaqueItem.add(empaque_evaporadoresItem);

        areaMenu.add(empaqueItem);

        procesosPosterioresItem.setText("Procesos Posteriores");

        procesosPosteriores_iluminariasItem.setText("Iluminarias");
        procesosPosteriores_iluminariasItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesosPosteriores_iluminariasItemActionPerformed(evt);
            }
        });
        procesosPosterioresItem.add(procesosPosteriores_iluminariasItem);

        areaMenu.add(procesosPosterioresItem);

        jMenuBar1.add(areaMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarBtnActionPerformed
        if (this.user.readUser(this.nombreTxt.getText(), this.contrasenaTxt.getText())) {
            this.nombreTxt.setEnabled(false);
            this.contrasenaTxt.setEnabled(false);
            this.entrarBtn.setEnabled(false);
            this.areaMenu.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Bienvenido "+ user.getNombre());
            this.cambioVentana(new MenuGui(this.user));
        }else{
            JOptionPane.showMessageDialog(null, "Algo ocurrio intenta nuevamente");
        }
        
    }//GEN-LAST:event_entrarBtnActionPerformed

    private void empaque_iluminariasItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empaque_iluminariasItemActionPerformed
        this.cambioVentana(new EmpaqueIluminariasGui(this.user));
    }//GEN-LAST:event_empaque_iluminariasItemActionPerformed

    private void trozado_iluminariasItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trozado_iluminariasItemActionPerformed
        this.cambioVentana(new TrozadosIluminariasGui(this.user));
    }//GEN-LAST:event_trozado_iluminariasItemActionPerformed

    private void procesosPosteriores_iluminariasItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesosPosteriores_iluminariasItemActionPerformed
        this.cambioVentana(new ProcesosPosterioresIluminariasGui(this.user));
    }//GEN-LAST:event_procesosPosteriores_iluminariasItemActionPerformed

    private void trozado_evaporadoresItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trozado_evaporadoresItemActionPerformed
        this.cambioVentana(new TrozadoEvaporadoresGui(this.user));
    }//GEN-LAST:event_trozado_evaporadoresItemActionPerformed

    private void empaque_evaporadoresItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empaque_evaporadoresItemActionPerformed
        this.cambioVentana(new EmpaqueEvaporadoresGui(this.user));
    }//GEN-LAST:event_empaque_evaporadoresItemActionPerformed

    private void menuGeneralItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGeneralItemActionPerformed
        this.cambioVentana(new MenuGui(this.user));
    }//GEN-LAST:event_menuGeneralItemActionPerformed

    private void logoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoBtnActionPerformed
    }//GEN-LAST:event_logoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
			new Main().setVisible(true);
		});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu areaMenu;
    private javax.swing.JPanel contenedorPanel;
    private javax.swing.JLabel contrasenaLbl;
    private javax.swing.JPasswordField contrasenaTxt;
    private javax.swing.JMenu empaqueItem;
    private javax.swing.JMenuItem empaque_evaporadoresItem;
    private javax.swing.JMenuItem empaque_iluminariasItem;
    private javax.swing.JButton entrarBtn;
    private javax.swing.JPanel formularioPanel;
    private javax.swing.JPanel ingresoPanel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton logoBtn;
    private javax.swing.JMenuItem menuGeneralItem;
    private javax.swing.JLabel nombreLbl;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JMenu procesosPosterioresItem;
    private javax.swing.JMenuItem procesosPosteriores_iluminariasItem;
    private javax.swing.JLabel tituloLbl;
    private javax.swing.JPanel tituloPanel;
    private javax.swing.JMenu trozadoItem;
    private javax.swing.JMenuItem trozado_evaporadoresItem;
    private javax.swing.JMenuItem trozado_iluminariasItem;
    // End of variables declaration//GEN-END:variables
}
