package Main;

import GUI.EmpaqueEvaporadoresGui;
import GUI.EmpaqueIluminariasGui;
import GUI.MenuGui;
import GUI.ProcesosPosterioresIluminariasGui;
import GUI.TrozadoEvaporadoresGui;
import GUI.TrozadosIluminariasGui;
import javax.swing.JOptionPane;
import GUI.components.JPanelAnimated;
import java.awt.Color;
import java.awt.GraphicsEnvironment;
import java.awt.Insets;
import java.awt.Rectangle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.Border;
import javax.swing.border.EtchedBorder;

/**
 *
 * @author CARR
 */
public class Main extends javax.swing.JFrame {

	public static Main instancia;
	public static BLL.Usuarios user;
	public JPanelAnimated panelContenedor;
    /**
     * Creates new form Main
     */
    public Main() {
		try {
			UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
			UIManager.getLookAndFeelDefaults().put("Panel.background", Color.WHITE);
			UIManager.getLookAndFeelDefaults().put("Button.background", new Color(25, 133, 172));
			UIManager.getLookAndFeelDefaults().put("Button.light", Color.WHITE);
			UIManager.getLookAndFeelDefaults().put("Button.foreground", Color.WHITE);
			UIManager.getLookAndFeelDefaults().put("InternalFrame.background", Color.WHITE);
			UIManager.getLookAndFeelDefaults().put("InternalFrame.activeTitleBackground", Color.WHITE);
			UIManager.getLookAndFeelDefaults().put("window", Color.WHITE);
			UIManager.getLookAndFeelDefaults().put("InternalFrame.activeTitleForeground", Color.BLACK);
			UIManager.getLookAndFeelDefaults().put("RadioButton.background", Color.WHITE);
			// Margen
			Border b = BorderFactory.createEtchedBorder(EtchedBorder.LOWERED);
			UIManager.put("TextField.margin", new Insets(5, 5, 5, 5));
			UIManager.put("PasswordField.margin", new Insets(5, 5, 5, 5));
			UIManager.put("Button.margin", new Insets(10, 5, 10, 5));
		} catch (ClassNotFoundException ex) {
			Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
		} catch (UnsupportedLookAndFeelException ex) {
			Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
		}
        initComponents();
        user = new BLL.Usuarios();
        instancia = this;
		panelContenedor = (JPanelAnimated) contenedorPanel;
    }
	
    public void cambioVentana(javax.swing.JPanel jp){
		panelContenedor.cambiarPanel(jp);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        ingresoPanel = new javax.swing.JPanel();
        tituloPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        tituloLbl = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        formularioPanel = new javax.swing.JPanel();
        nombreLbl = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        contrasenaLbl = new javax.swing.JLabel();
        contrasenaTxt = new javax.swing.JPasswordField();
        entrarBtn = new javax.swing.JButton();
        contenedorPanel = new JPanelAnimated();
        jMenuBar1 = new javax.swing.JMenuBar();
        areaMenu = new javax.swing.JMenu();
        menuGeneralItem = new javax.swing.JMenuItem();
        trozadoItem = new javax.swing.JMenu();
        trozado_iluminariasItem = new javax.swing.JMenuItem();
        trozado_evaporadoresItem = new javax.swing.JMenuItem();
        empaqueItem = new javax.swing.JMenu();
        empaque_iluminariasItem = new javax.swing.JMenuItem();
        empaque_evaporadoresItem = new javax.swing.JMenuItem();
        procesosPosterioresItem = new javax.swing.JMenu();
        procesosPosteriores_iluminariasItem = new javax.swing.JMenuItem();

        ingresoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ingresoPanel.setLayout(new java.awt.GridBagLayout());

        tituloPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        tituloPanel.setPreferredSize(new java.awt.Dimension(411, 50));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        tituloLbl.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        tituloLbl.setForeground(new java.awt.Color(75, 113, 125));
        tituloLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLbl.setText("DEMO");
        tituloLbl.setBorder(null);
        tituloLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tituloLbl);

        logo.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        logo.setForeground(new java.awt.Color(75, 113, 125));
        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sopraval.png"))); // NOI18N
        logo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        logo.setPreferredSize(logo.getPreferredSize());
        jPanel1.add(logo);

        tituloPanel.add(jPanel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.ipady = 72;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        ingresoPanel.add(tituloPanel, gridBagConstraints);

        formularioPanel.setLayout(new java.awt.GridBagLayout());

        nombreLbl.setText("Nombre: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 11, 0);
        formularioPanel.add(nombreLbl, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 11, 0);
        formularioPanel.add(nombreTxt, gridBagConstraints);

        contrasenaLbl.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        formularioPanel.add(contrasenaLbl, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        formularioPanel.add(contrasenaTxt, gridBagConstraints);

        entrarBtn.setText("Entrar");
        entrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 180;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        formularioPanel.add(entrarBtn, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        ingresoPanel.add(formularioPanel, gridBagConstraints);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        contenedorPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        /*

        */

        javax.swing.GroupLayout contenedorPanelLayout = new javax.swing.GroupLayout(contenedorPanel);
        contenedorPanel.setLayout(contenedorPanelLayout);
        contenedorPanelLayout.setHorizontalGroup(
            contenedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );
        contenedorPanelLayout.setVerticalGroup(
            contenedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );

        getContentPane().add(contenedorPanel);

        areaMenu.setText("AREA");
        areaMenu.setEnabled(false);

        menuGeneralItem.setText("Menu General");
        menuGeneralItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGeneralItemActionPerformed(evt);
            }
        });
        areaMenu.add(menuGeneralItem);

        trozadoItem.setText("Trozado");

        trozado_iluminariasItem.setText("Iluminarias");
        trozado_iluminariasItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trozado_iluminariasItemActionPerformed(evt);
            }
        });
        trozadoItem.add(trozado_iluminariasItem);

        trozado_evaporadoresItem.setText("Evaporadores");
        trozado_evaporadoresItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trozado_evaporadoresItemActionPerformed(evt);
            }
        });
        trozadoItem.add(trozado_evaporadoresItem);

        areaMenu.add(trozadoItem);

        empaqueItem.setText("Empaque");

        empaque_iluminariasItem.setText("Iluminarias");
        empaque_iluminariasItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empaque_iluminariasItemActionPerformed(evt);
            }
        });
        empaqueItem.add(empaque_iluminariasItem);

        empaque_evaporadoresItem.setText("Evaporadores");
        empaque_evaporadoresItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empaque_evaporadoresItemActionPerformed(evt);
            }
        });
        empaqueItem.add(empaque_evaporadoresItem);

        areaMenu.add(empaqueItem);

        procesosPosterioresItem.setText("Procesos Posteriores");

        procesosPosteriores_iluminariasItem.setText("Iluminarias");
        procesosPosteriores_iluminariasItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesosPosteriores_iluminariasItemActionPerformed(evt);
            }
        });
        procesosPosterioresItem.add(procesosPosteriores_iluminariasItem);

        areaMenu.add(procesosPosterioresItem);

        jMenuBar1.add(areaMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarBtnActionPerformed
        if (Main.user.readUser(this.nombreTxt.getText(), this.contrasenaTxt.getText())) {
            this.nombreTxt.setEnabled(false);
            this.contrasenaTxt.setEnabled(false);
            this.entrarBtn.setEnabled(false);
            this.areaMenu.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Bienvenido "+ user.getNombre());
            this.cambioVentana(new MenuGui());
        }else{
            JOptionPane.showMessageDialog(null, "Algo ocurrio intenta nuevamente");
        }
        
    }//GEN-LAST:event_entrarBtnActionPerformed

    private void empaque_iluminariasItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empaque_iluminariasItemActionPerformed
        this.cambioVentana(new EmpaqueIluminariasGui());
    }//GEN-LAST:event_empaque_iluminariasItemActionPerformed

    private void trozado_iluminariasItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trozado_iluminariasItemActionPerformed
        this.cambioVentana(new TrozadosIluminariasGui());
    }//GEN-LAST:event_trozado_iluminariasItemActionPerformed

    private void procesosPosteriores_iluminariasItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesosPosteriores_iluminariasItemActionPerformed
        this.cambioVentana(new ProcesosPosterioresIluminariasGui());
    }//GEN-LAST:event_procesosPosteriores_iluminariasItemActionPerformed

    private void trozado_evaporadoresItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trozado_evaporadoresItemActionPerformed
        this.cambioVentana(new TrozadoEvaporadoresGui());
    }//GEN-LAST:event_trozado_evaporadoresItemActionPerformed

    private void empaque_evaporadoresItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empaque_evaporadoresItemActionPerformed
        this.cambioVentana(new EmpaqueEvaporadoresGui());
    }//GEN-LAST:event_empaque_evaporadoresItemActionPerformed

    private void menuGeneralItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGeneralItemActionPerformed
        this.cambioVentana(new MenuGui());
    }//GEN-LAST:event_menuGeneralItemActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
		GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
		Rectangle bounds = env.getMaximumWindowBounds();
		contenedorPanel.setBounds(bounds);
		cambioVentana(ingresoPanel);
    }//GEN-LAST:event_formWindowOpened

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
		revalidate();
    }//GEN-LAST:event_formComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
			new Main().setVisible(true);
		});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu areaMenu;
    private javax.swing.JPanel contenedorPanel;
    private javax.swing.JLabel contrasenaLbl;
    private javax.swing.JPasswordField contrasenaTxt;
    private javax.swing.JMenu empaqueItem;
    private javax.swing.JMenuItem empaque_evaporadoresItem;
    private javax.swing.JMenuItem empaque_iluminariasItem;
    private javax.swing.JButton entrarBtn;
    private javax.swing.JPanel formularioPanel;
    private javax.swing.JPanel ingresoPanel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JMenuItem menuGeneralItem;
    private javax.swing.JLabel nombreLbl;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JMenu procesosPosterioresItem;
    private javax.swing.JMenuItem procesosPosteriores_iluminariasItem;
    private javax.swing.JLabel tituloLbl;
    private javax.swing.JPanel tituloPanel;
    private javax.swing.JMenu trozadoItem;
    private javax.swing.JMenuItem trozado_evaporadoresItem;
    private javax.swing.JMenuItem trozado_iluminariasItem;
    // End of variables declaration//GEN-END:variables
}
